language: node_js
node_js:
  - "4.0"
services:
  - redis-server
install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - PATH=$PATH:~/bin
  - lein
  - lein npm install

script: lein cljsbuild once
