language: node_js
node_js:
  - "0.12"
  - "iojs"
services:
  - redis-server
install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - PATH=$PATH:~/bin
  - lein
  - lein npm install

script: NODE_PATH=./node_modules lein cljsbuild test
