language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - PATH=$PATH:~/bin
  - lein
  - sudo apt-get install redis-server

script: NODE_PATH=./node_modules lein cljsbuild test
