language: node_js
node_js:
  - "5.1"
services:
  - redis-server
install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - PATH=$PATH:~/bin
  - lein
  - lein deps

script: lein cljsbuild once
