language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - source ~/.bash_profile
  - sudo apt-get install redis

script: lein cljsbuild test
