language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

install:
  - sudo apt-add-repository ppa:gautambt/leiningen2
  - sudo apt-get update
  - sudo apt-get install redis leinigen

script: lein cljsbuild test
